### ISSUE TITLE
自定义视频采集 demo 中，用前鏡頭推流時，拉流端看到的畫面會左右相反

### ISSUE THREAD

**Issue by tl-yen** [zegoim/zego-express-example-topics-android#1]
## 發生的狀況
用前鏡頭推流時，**拉流端看到的畫面會左右相反**
> `setVideoMirrorMode(ONLY_PUBLISH_MIRROR, ZegoPublishChannel.MAIN);` 和 `setVideoMirrorMode(NO_MIRROR, ZegoPublishChannel.MAIN);` 都無效

## 使用的功能
Custom capture 的 camera(yuv) 

## demo 版本
1a3e86226bb7179e9986e6e4aa2eedd8d6637328 

## 重現步驟
* [把 `VideoCaptureFromCamera#setFrontCam(int)`從 `private` 改成 `public`](https://github.com/zegoim/zego-express-example-topics-android/blob/master/ZegoExpressExample/video/CustomVideoCapture/src/main/java/im/zego/videocapture/camera/VideoCaptureFromCamera.java#L146)
![image](https://user-images.githubusercontent.com/54790593/86429907-6be69500-bd23-11ea-9c2f-1439cb3def60.png)

* [在`ZGVideoCaptureDemoUI`加上`((VideoCaptureFromCamera)videoCapture).setFrontCam(1);`](https://github.com/zegoim/zego-express-example-topics-android/blob/master/ZegoExpressExample/video/CustomVideoCapture/src/main/java/im/zego/videocapture/ui/ZGVideoCaptureDemoUI.java#L110-L111)
![image](https://user-images.githubusercontent.com/54790593/86429916-71dc7600-bd23-11ea-87f8-36361579edbe.png)

* 啟動 demo app
* 點擊 Advanced features 的 **Custom capture**
* 點擊 Collection source 的 **camera(yuv)**
* 點擊 **StartPlay**
* (使用前鏡頭中)拿起手機拍攝自己並舉手
![20200703-113032](https://user-images.githubusercontent.com/54790593/86429609-aac81b00-bd22-11ea-833b-7ddca9591669.gif)

**Comment by tl-yen** [comment]
Quick start 功能，呼叫 `setVideoMirrorMode(XXX, MAIN)` 就有效果。
我猜貴公司的「自定义视频采集」有 bug。
<img width="959" alt="Screenshot 2020-07-03 at 17 52 03" src="https://user-images.githubusercontent.com/54790593/86457255-f3e59280-bd55-11ea-993f-2e908e19872e.png">

**Comment by JohnsonCYS** [comment]
自定义采集默认拉流渲染出来的画面就是和采集的画面成镜像关系。这边测试最新的示例demo，通过setVideoMirrorMode设置，可以达到设置拉流画面方向的效果。您可以尝试使用最新的示例demo进行设置。

**Comment by tl-yen** [comment]
> 通过setVideoMirrorMode设置，可以达到设置拉流画面方向的效果。您可以尝试使用最新的示例demo进行设置。

![image](https://user-images.githubusercontent.com/54790593/104400104-f50d3d00-558c-11eb-9a2d-d1afa6a60b8f.png)
